# Generated by Django 4.1.4 on 2023-01-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_full_name', models.CharField(max_length=100, verbose_name='Country full name')),
                ('country_short_name', models.CharField(max_length=3, verbose_name='Country short name')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='YearProdaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_prodaction', models.CharField(max_length=4, verbose_name='Year prodaction')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('overview', models.CharField(max_length=2500, verbose_name='Overview')),
                ('duration', models.CharField(max_length=4, verbose_name='Duration')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
                ('year_prodaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearprodaction')),
            ],
        ),
    ]
