# Generated by Django 4.1.4 on 2023-01-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year_prodaction_id',
            field=models.CharField(max_length=10, verbose_name='Year prodaction id'),
        ),
    ]
