# Generated by Django 4.1.4 on 2023-01-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearprodaction',
            name='year_prodaction',
            field=models.CharField(max_length=4, verbose_name='Year prodaction'),
        ),
    ]
