# Generated by Django 4.1.4 on 2023-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_yearprodaction_year_prodaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Middle name'),
        ),
    ]
