# Generated by Django 4.1.4 on 2023-01-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_yearprodaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='year_prodaction_id',
            new_name='year_prodaction',
        ),
    ]
