# Generated by Django 4.1.4 on 2023-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_film_year_prodaction_film_year_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='remark',
            field=models.TextField(null=True, verbose_name='Remark'),
        ),
    ]
