# Generated by Django 4.1.4 on 2023-01-25 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_film_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='own_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Own rating'),
        ),
    ]
